[workspace]
members = [
	"projects/empty",
	"sys",
	"util/linked_list_allocator"
]

[package]
name = "embedded_wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
