[workspace]
members = [
	"embedded_wasm",
	"embedded_wasm/derive",
	"projects/sys",
	"projects/shared",
	"runner/desktop",
]
default-members = ["runner/desktop"]
exclude = [
	"projects/blink",
	"projects/async_example",
	"runner/rp2040",
]
