[workspace]
members = [
	"embedded_wasm",
	"projects/sys",
	"projects/shared",
	"runner/desktop",
	"utils/linked_list_allocator",
]
default-members = ["runner/desktop"]
exclude = [
	"projects/empty",
	"runner/rp2040",
]
